name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: yarn
    - name: Deploy
      run: |
        yarn run ng deploy --name="Alpha Barry" --email=alpha.mt.barry@gmail.com
        echo test, and deploy your project.
      env:
        CI: true
        GH_TOKEN: ${{secrets.GH_TOKEN}}
