name: CI/CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: yarn
    - name: Lint and test
      run: |
        yarn lint
        yarn test --runInBand
    - name: Builds
      run: |
        yarn run build --prod
    - name: Gh pages deploy
      # TODO: run only on master branch
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        yarn run deploy
